### ISSUE TITLE
gowin_pack broken -> apicula 0.3.1 needed

### ISSUE THREAD

**Issue by RGD2** [YoWASP/nextpnr#14]
The problem with gowin_pack presents as in ticket YosysHQ/apicula#99 and has been fixed in apicula 0.3.1

But `apycula=0.3` is set as dependancy for the pip package yowasp-nextpnr-gowin 0.3.dev303, which prevents new installs getting a working version (where I tripped over it).
 
Recommend changing that dependancy to  `apycula>=0.3<0.4` so any other minor fixes like this to apycula get picked up and fixed without requiring further change to the dependancy setting here.

For now a workaround is  `pip install -U apycula` which then complains that yowasp-nextpnr-gowin is incompatible because it requires apycula=0.3, but otherwise works.

**Comment by whitequark** [comment]
Apycula does not, to my knowledge, provide any guarantee of chipdb compatibility between versions. So this is not possible.

**Comment by pepijndevos** [comment]
The build script takes the last version of apycula from pypi and encodes that as a dependency so that the versions always match. So the next release will have the latest apycula as a dependency. There is indeed no guarantee about backwards compatibility, so while it might work most of the time, it's better to ensure matching versions.

**Comment by RGD2** [comment]
Okay, then if apicula bumps, the build script also ought to bump, each time a fresh version hits pypi. It's a bit embarrassing to have something broken for three weeks when it could have been fixed. 

Apycula 0.3.1 was on pypi April 12th, and it's obviously only a non-breaking minor release update to fix this issue; otherwise it'd have been version 0.4, if it did break anything. 

Is there any problem with at least trying to generate a new, matching version as soon as it bumps, for minor point releases like this? Does this 0.3.1 bump really actually break compatibilty, or are you just assuming it does? Is there really much danger in using a dependancy code like `>=y.x,<y.(x-1)`?  (where y.x is a match for current minor version).


Surely if they're just going to drop a `.1` on the end of their version, for a release which is only a fix, and not a break, it shouldn't be difficult to just regen a matching version assuming no breakage? That way, you don't need to intervene when your dependancy is just fixing a little gaffe like that, and your own release gets fixed about as quickly, and isn't stale for three weeks or until someone trips over it. Beware newcomers can and will trip up on minor things like this, and rather than bothering to open a ticket, will often just discard the whole project into the 'too hard' bin. This is never good for a project. They'll remember that YoWASP is unreliable, but the fresh versions elsewhere worked, and just put it down to YoWASP not being ready to depend on.

Odds are, if they do break something and mislabel it as just a `version_string+'.1' `, then you could complain, and have them re-release a non-breaking minor version (perhaps merged from an older commit, before the blamed one) with just another minor point increment. 

This is how version numbers are supposed to work. The whole point is to allow the author to fix tiny errors and omissions like this and just increment the minor number so everyone gets the fix, whilst being able to trust that an update like this does NOT risk breaking compatibility.

You're in the sticky situation of needing to be closly-coupled to the bleeding edge of your main dependancy. That means, I think, that you should just have your build system automatically bump for at least minor point updates - anything in after the second period in the version number. It shouldn't take a ticket.

**Comment by RGD2** [comment]
PS - almost forgot to say: Keep up the fantastic work guys! This project is truely great, and I was blown away by how trivial it made getting dependancies for gowin FPGA support onto both my laptop (corporate one, but debian/WSL2 works well enough) and an embedded SBC (the usual suspect - a raspi3), for the purposes of allowing an FPGA-based fuel controller to run a technology which essentally will allow nearly-unmodified Diesel engines (a gen-set in this case) to run on stranded solar power, captured into chemical energy and bottled just like LPG -- but with zero carbon.

I am still using the gowin ide for now, but the control stuff I do is so simple and dumb (fixed pipeline multicycle at low clock rates - it's really more about reliably, zero timing variation, and being able to absorb more jobs without disturbing existing timing that makes FPGA's a much better fit than MCU's for controlling engines) that I expect YoWASP to be usable very quickly. 

Since this thing is a prototype that may go places, being able to build both the source and all the required dev tools 'into the box' by just letting an SBC embed along for the ride is fantastic - it allows for an ECU which is 'service/reuse friendly', at least to anyone who inherits the box, which is a major advantage over the traditional 'little irreparable black box ECU' which has been plaguing automotive electrical repair as long as they've been about. 

This is exactly the way of doing industrial electronics that I'd want, were I taking it to, say, Mars. I wouldn't want to end up with a blackbox in my oxygen plant that's irrepairable and unretaskable without a special laptop with a special software tool with a special time-limited phone-home license that wants to do FPGA recompilation back on the software-company's compute cloud!

You should be proud.

**Comment by whitequark** [comment]
> Does this 0.3.1 bump really actually break compatibilty, or are you just assuming it does?

Since it is not guaranteed that a bump like this will never break compatibility I assume that it does to be on the safe side.

> They'll remember that YoWASP is unreliable, but the fresh versions elsewhere worked, and just put it down to YoWASP not being ready to depend on.

This is exactly the kind of scenario I'm trying to avoid. Right now, you get an error from your package manager that clearly indicates that there may be a compatibility issue; and prompts you to open a ticket, or perhaps avoid using this package entirely. These are acceptable outcomes. If there _was_ an incompatibility, and it was silently accepted by the package manager, then you could silently get a bad bitstream, which is a significantly worse outcome: it would result in a lot more wasted time, and is a bigger breach of trust.

> This is how version numbers are supposed to work. The whole point is to allow the author to fix tiny errors and omissions like this and just increment the minor number so everyone gets the fix, whilst being able to trust that an update like this does NOT risk breaking compatibility.

Bluntly, I do not care how version numbers are 'supposed' to work. I have asked @pepijndevos how they work, and they do not work like that for Apycula. YoWASP will change its policy if and only if Apycula changes their policy to provide the necessary guarantees.

**Comment by whitequark** [comment]
> Okay, then if apicula bumps, the build script also ought to bump, each time a fresh version hits pypi. It's a bit embarrassing to have something broken for three weeks when it could have been fixed.

This _does_ actually happen; YoWASP runs nightly builds and uploads the artifacts to https://test.pypi.org/. I have also started a build that would upload to https://pypi.org/ (https://pypi.org/project/yowasp-nextpnr-gowin/0.3.post31.dev324/) as soon as you opened this ticket.

Could I upload every nightly build to https://pypi.org/ anyway? Unfortunately not, PyPI limits the total size of the project to 10 GiB and every `yowasp-nextpnr-ice40` release is 80 MiB, so we'll run out of space in about 4 months of daily nextpnr commits. This is why it's done manually.

**Comment by RGD2** [comment]
> This is exactly the kind of scenario I'm trying to avoid. 
You didn't. 

> Right now, you get an error from your package manager that clearly indicates that there may be a compatibility issue;
Right now, everything a-OK - no errors, we're back to what you were trying to avoid. 0.3.post31.dev324 is just fine.

But the thing is, I didn't get here directly because of that error. There was no error when I installed yowasp-nextpnr-gowin.

What happened was that I installed yowasp-nextpnr-gowin, and it pulled in the broken 0.3 version of apycula, without an error. Everything seemed good. 

But the first time I tried to use it,  gowin_pack failed with an obtuse error. Because it was broken. This also would have happened to everyone else, most notably including everyone giving yowasp a try for gowin.

So I went hunting the problem with Apicula. It seemed the sort of thing that would honestly not have been your fault - it didn't even occur to me to come here first. 

The only reference I found, after digging through both open, and **closed** tickets, was something that seemed a match. Pn that ticket, it was resolved with:

> Try the master branch

And hence clearly already fixed before catkira reported it on the second of April.

I then forced apycula with the manual install -U line 'workaround' I quoted above. 

At **that** point, having already solved my problem (when I noted that Apicula was indeed fixed) I realised the problem was that you were out of date - and now got the incompatibility warning from pip.

Looking at the last-published date for apicula 0.3.1 on pypi, I was astonished to see it **three weeks stale**. 

How could this be? Isn't the point of YoWASP to be automatically rebuilt? Clearly someone isn't respecting how the version numbering system convention works.

> Bluntly, I do not care how version numbers are 'supposed' to work. 

🤷‍♂️  Sure. Though in this case, they **did** work how they were supposed to. The 0.3 release was essentially a mistake, to be overridden everywhere downstream with 0.3.1 without risk of new breakage, as indicated by the version number convention.

> ... we'll run out of space in about 4 months of daily nextpnr commits. 
>This is why it's done manually.

Okay, I only mean to suggest that whenever apycula goes to a greater step, which now would be >0.3.1, but <0.4, that the upload ought to go ahead without requiring manual intervention, as an exception to handle this sort of fix, which is fairly likely to be a common occurrence, the state of art being what it is right now. 

That way you're not waiting for the good fortunes of good Samaritan appearing to contribute time to submit a ticket appearing to prompt you to fix something that you otherwise could have avoided breaking. 

Deps in your pypi packages indeed ought to stay an equality match; I didn't mean to imply that it shouldn't. 

My apologies for miscommunication - that's on me and my poor writing. 

Nightly is indeed overkill, and not doing them is reasonable given your limitations. 

But I think a point update push from above like this is probably always urgent enough to make it an exception.

Thanks again. 

And by all means things are fine now - ticket closed, issue resolved, all is well. 👍

**Comment by whitequark** [comment]
> Okay, I only mean to suggest that whenever apycula goes to a greater step, which now would be >0.3.1, but <0.4, that the upload ought to go ahead without requiring manual intervention, as an exception to handle this sort of fix, which is fairly likely to be a common occurrence, the state of art being what it is right now.
>
> Deps in your pypi packages indeed ought to stay an equality match; I didn't mean to imply that it shouldn't.

There's now infrastructure (https://github.com/whitequark/track-pypi-dependency-version/) to handle this sort of thing, though it's not currently used for Apycula.
